name: Actions Workflow

on: [push,pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: CheckOut
        uses: actions/checkout@v1
      - name: simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Yuvaraj
      - name: Greeting time
        run: echo "${{ steps.greet.outputs.time }}"