name: Shell Commands

on:
  push:
    branches:
      - master
      - "feature/*"
      - "feature/**"
      - "!feature/featC"
    tags:
      - "v1.*"
    paths:
      - "**.js"

  # repository_dispatch:
  #  types: [build]
  # schedule:
  #  - cron: 0/5 * * * *
  #  - cron: 0/6 * * * *
  # push:
  # pull_request:
  # types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: echo a String
        run: echo "Hello World "
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory PowerShell
        run: get-location
      - name: Directory bash
        run: pwd
        shell: bash